from patologiaveterinaria.model.patologista_model import PatologistaModel
from patologiaveterinaria.model.especie_model import EspecieModel
from patologiaveterinaria.model.animal_model import AnimalModel
from patologiaveterinaria.model.proprietario_model import ProprietarioModel
from patologiaveterinaria.model.tecnico_model import TecnicoModel
from patologiaveterinaria.model.estado_model import EstadoModel
from patologiaveterinaria.model.cidade_model import CidadeModel
from patologiaveterinaria.model.endereco_model import EnderecoModel
