# Generated by Django 2.2.9 on 2019-12-19 17:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('idade_do_animal', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=5, null=True)),
                ('cor_pelagem', models.CharField(blank=True, max_length=50)),
                ('dt_cadastro', models.DateField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('complemento', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='BairroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='EspecieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especie', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
            },
        ),
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=100)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='ProprietarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=150)),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('celular', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Proprietario',
                'verbose_name_plural': 'Proprietarios',
            },
        ),
        migrations.CreateModel(
            name='TipoLaudoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_laudo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Laudo',
                'verbose_name_plural': 'Tipos de Laudo',
            },
        ),
        migrations.CreateModel(
            name='VeterinarioResponsavelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_veterinario', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('crmv', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Veterinário Responsável',
                'verbose_name_plural': 'Veterinários Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='RuaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rua', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('id_bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.BairroModel')),
            ],
            options={
                'verbose_name': 'Rua',
                'verbose_name_plural': 'Ruas',
            },
        ),
        migrations.CreateModel(
            name='RequisicaoLaudoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rghv', models.IntegerField(blank=True, null=True)),
                ('dt_coleta', models.DateField()),
                ('material_enviado', ckeditor.fields.RichTextField()),
                ('historico_clinico', ckeditor.fields.RichTextField()),
                ('descricao_macroscopica', ckeditor.fields.RichTextField()),
                ('scan_figura_ficha_clinica', models.ImageField(blank=True, upload_to='imagem_ficha_clinica')),
                ('responsavel_recebimento', models.CharField(blank=True, max_length=100)),
                ('dt_recebimento', models.DateField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.AnimalModel')),
                ('tipo_de_laudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.TipoLaudoModel')),
            ],
        ),
        migrations.CreateModel(
            name='RacaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_raca', models.CharField(max_length=100)),
                ('id_especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.EspecieModel')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='CidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.EstadoModel')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.AddField(
            model_name='bairromodel',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.CidadeModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.ProprietarioModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.RacaModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.RuaModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='veterinario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.VeterinarioResponsavelModel'),
        ),
    ]
