# Generated by Django 2.2.9 on 2019-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudoPatologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarioPatologistaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_veterinario_patologista', models.CharField(blank=True, max_length=150, null=True)),
                ('formacao', models.CharField(blank=True, max_length=100, null=True)),
                ('crmv', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Veterinários Patologista',
                'verbose_name': 'Veterinário Patologista',
            },
        ),
    ]
