# Generated by Django 2.2.9 on 2019-12-19 18:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laudoPatologia', '0002_veterinariopatologistamodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicaolaudomodel',
            options={'verbose_name': 'Requisição', 'verbose_name_plural': 'Requisições'},
        ),
        migrations.CreateModel(
            name='LaudoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_microscopica', ckeditor.fields.RichTextField()),
                ('diagnostico_morfologico', ckeditor.fields.RichTextField()),
                ('sistemas', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cardiovascular', 'Cardiovascular'), ('Pulmonar', 'Pulmonar'), ('Digestivo', 'Digestivo'), ('Endócrino', 'Endócrino'), ('Nervoso', 'Nervoso'), ('Reprodutivo', 'Reprodutivo'), ('Muscular', 'Muscular'), ('Esquelético', 'Esquelético'), ('Tegumentar', 'Tegumentar'), ('Excretor', 'Excretor')], max_length=104, null=True)),
                ('etiologia', models.CharField(blank=True, max_length=300, null=True)),
                ('diagnostico_final', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('comentarios', ckeditor.fields.RichTextField()),
                ('dt_laudo', models.DateField()),
                ('id_requisicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laudoPatologia.RequisicaoLaudoModel')),
                ('veterinario_patologista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.VeterinarioPatologistaModel')),
            ],
            options={
                'verbose_name': 'Laudo',
                'verbose_name_plural': 'Laudos',
            },
        ),
        migrations.CreateModel(
            name='ImagensModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_imagem', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('id_laudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.LaudoModel')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
