# Generated by Django 2.2.9 on 2019-12-24 12:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('laudoPatologia', '0003_auto_20191219_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.BairroModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.CidadeModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='id_especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.EspecieModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudoPatologia.EstadoModel'),
        ),
    ]
