from .usuario_form import UserForm
from .estado_form import EstadoForm
from .cidade_form import CidadeForm
from .bairro_form import BairroForm
from .rua_form import RuaForm
from .proprietario_form import ProprietarioForm
from .veterinario_responsavel_form import VeterinarioResponsavelForm
from .especie_form import EspecieForm
from .raca_form import RacaForm
from .animal_form import AnimalForm
from .animal_update_form import AnimalUpdateForm
from .tipo_laudo_form import TipoLaudoForm
from .requisicao_laudo_form import RequisicaoLaudoForm
from .veterinario_patologista_form import VeterinarioPatologistaForm
from .laudo_form import LaudoForm
from .imagem_form import ImagemForm