# Generated by Django 2.2 on 2019-04-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patologiaveterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodel',
            name='comentarios',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
