# Generated by Django 2.2 on 2019-04-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patologiaveterinaria', '0001_initial'),
    ]

    operations = [
    ]
