# Generated by Django 2.2 on 2019-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patologiaveterinaria', '0003_tipolaudomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='bairro',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='endereco',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
