from patologiaveterinaria.form.patologista_form import PatologistaForm
from patologiaveterinaria.form.animal_form import AnimalForm
from patologiaveterinaria.form.proprietario_form import ProprietarioForm