from laudosMedvet.models.usuario_model import UsuarioModel
from laudosMedvet.models.laudo_model import LaudoModel
from laudosMedvet.models.tipo_laudo_model import TipoLaudoModel

from laudosMedvet.models.especie_model import EspecieModel
from laudosMedvet.models.proprietario_model import ProprietarioModel
from laudosMedvet.models.veterinario_responsavel_model import VeterinarioresponsavelModel
from laudosMedvet.models.animal_model import AnimalModel


from laudosMedvet.models.regiao_federal_model import RegiaoFederalModel
from laudosMedvet.models.estado_model import EstadoModel
from laudosMedvet.models.regiao_estado_model import RegiaoEstadoModel
from laudosMedvet.models.cidade_model import CidadeModel
from laudosMedvet.models.bairro_model import BairroModel
from laudosMedvet.models.rua_model import RuaModel

from laudosMedvet.models.imagem_model import ImagensModel
from laudosMedvet.models.requisicao_laudo_model import RequisicaoLaudoModel
from laudosMedvet.models.raca_model import RacaModel
