from patologiaveterinaria.view.index_view import IndexView
from patologiaveterinaria.view.usuario_view import CadastroUsuarioView, LoginView, LogoutView
from patologiaveterinaria.view.principal_view import PaginaPrincipal
from patologiaveterinaria.view.cadastrar_animal_view import CadastrarAnimal