from patologiaveterinaria.view.login_user_view import LoginUserView
from patologiaveterinaria.view.usuario_view import CadastroUsuarioView, LoginView, LogoutView
from patologiaveterinaria.view.principal_view import PaginaPrincipal
from patologiaveterinaria.view.cadastrar_animal_view import CadastrarAnimal
from patologiaveterinaria.view.laudo_view import CadastrarLaudo
from patologiaveterinaria.view.principal_view import MostraAnimal