# Generated by Django 2.2 on 2019-05-15 14:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BairroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EspecieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especie', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Espécies',
                'verbose_name': 'Espécie',
            },
        ),
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoFederalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regiao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLaudoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_laudo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VeterinarioresponsavelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_veterinario', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('crmv', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rua', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=40)),
                ('id_bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.BairroModel')),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoEstadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regiao', models.CharField(max_length=50)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.EstadoModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProprietarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=150)),
                ('data_nasc', models.DateField(verbose_name='Data Nascimento')),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=40)),
                ('celular', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=250, null=True)),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.RuaModel')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_enviado', models.CharField(max_length=500)),
                ('historico_clinico', models.TextField()),
                ('descricao_macroscopica', models.TextField()),
                ('descricao_microscopica', models.TextField()),
                ('diagnostico_morfologico', models.TextField()),
                ('comentarios', models.TextField()),
                ('tipo_laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laudosMedvet.TipoLaudoModel')),
            ],
        ),
        migrations.CreateModel(
            name='ImagensModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_imagem', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laudosMedvet.LaudoModel')),
            ],
        ),
        migrations.AddField(
            model_name='estadomodel',
            name='id_regiao_federal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.RegiaoFederalModel'),
        ),
        migrations.CreateModel(
            name='CidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100)),
                ('id_regiao_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.RegiaoEstadoModel')),
            ],
        ),
        migrations.AddField(
            model_name='bairromodel',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.CidadeModel'),
        ),
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('sexo', models.CharField(max_length=1)),
                ('raca', models.CharField(max_length=100)),
                ('cor_pelagem', models.CharField(max_length=50)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('numero', models.IntegerField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laudosMedvet.EspecieModel')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laudosMedvet.ProprietarioModel')),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.RuaModel')),
                ('veterinario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laudosMedvet.VeterinarioresponsavelModel')),
            ],
        ),
    ]
