# Generated by Django 2.2.4 on 2019-11-01 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaolaudomodel',
            name='historico_clinico',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
