# Generated by Django 2.2.4 on 2019-09-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietariomodel',
            name='celular',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='complemento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='rg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.RuaModel'),
        ),
        migrations.AlterField(
            model_name='proprietariomodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
