# Generated by Django 2.2.2 on 2019-08-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudomodel',
            name='sistemas',
            field=models.CharField(default='desconhecido', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisicaolaudomodel',
            name='rghv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
