# Generated by Django 2.2 on 2019-05-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalmodel',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='regiaofederalmodel',
            options={'verbose_name': 'Regiões Federais', 'verbose_name_plural': 'Região Federal'},
        ),
    ]
