# Generated by Django 2.2.4 on 2019-11-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensmodel',
            name='imagem',
            field=models.ImageField(default='', upload_to='imagens'),
            preserve_default=False,
        ),
    ]
