# Generated by Django 2.2.4 on 2019-08-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodel',
            name='etiologia',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
