# Generated by Django 2.2 on 2019-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalmodel',
            name='numero',
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='sexo',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
