# Generated by Django 2.2 on 2019-05-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.EspecieModel'),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.ProprietarioModel'),
        ),
        migrations.AlterField(
            model_name='animalmodel',
            name='veterinario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.VeterinarioresponsavelModel'),
        ),
    ]
