# Generated by Django 2.2 on 2019-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0002_auto_20190524_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='data_nasc',
            field=models.DateField(),
        ),
    ]
