# Generated by Django 2.2.4 on 2019-11-01 16:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0002_auto_20191101_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaolaudomodel',
            name='descricao_macroscopica',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='requisicaolaudomodel',
            name='material_enviado',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
