# Generated by Django 2.2.4 on 2019-09-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0002_auto_20190902_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laudosMedvet.EspecieModel'),
        ),
    ]
