# Generated by Django 2.2 on 2019-05-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0002_auto_20190509_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especiemodel',
            options={'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
    ]
