# Generated by Django 2.2.4 on 2019-08-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0002_auto_20190823_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodel',
            name='sistemas',
            field=models.CharField(max_length=500),
        ),
    ]
