# Generated by Django 2.2 on 2019-05-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0003_auto_20190509_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especiemodel',
            old_name='especie',
            new_name='nome_especie',
        ),
    ]
