# Generated by Django 2.2.4 on 2019-09-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0003_animalmodel_especie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalmodel',
            old_name='especie',
            new_name='id_especie',
        ),
    ]
