# Generated by Django 2.2.4 on 2019-08-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('laudosMedvet', '0003_auto_20190823_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'permissions': (('pode_acessar_estado', 'Pode acessar estado'),),
            },
        ),
    ]
