# Generated by Django 2.2.4 on 2019-11-01 17:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0003_auto_20191101_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodel',
            name='comentarios',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='laudomodel',
            name='descricao_microscopica',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='laudomodel',
            name='diagnostico_final',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laudomodel',
            name='diagnostico_morfologico',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
