# Generated by Django 2.2.4 on 2019-09-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0004_auto_20190906_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.BairroModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.CidadeModel'),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudosMedvet.EstadoModel'),
        ),
    ]
