# Generated by Django 2.2.4 on 2019-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0004_permissaomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodel',
            name='sistemas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
