# Generated by Django 2.2.4 on 2019-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0005_auto_20190828_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodel',
            name='sistemas',
            field=models.CharField(blank=True, choices=[('Cardiovascular', 'Cardiovascular'), ('Pulmonar', 'Pulmonar'), ('Digestivo', 'Digestivo'), ('Endócrino', 'Endócrino'), ('Nervoso', 'Nervoso'), ('Reprodutivo', 'Reprodutivo'), ('Muscular', 'Muscular'), ('Esquelético', 'Esquelético'), ('Tegumentar', 'Tegumentar'), ('Excretor', 'Excretor')], max_length=500, null=True),
        ),
    ]
