# Generated by Django 2.2.4 on 2019-08-29 16:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0006_auto_20190829_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudomodel',
            name='sistemas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cardiovascular', 'Cardiovascular'), ('Pulmonar', 'Pulmonar'), ('Digestivo', 'Digestivo'), ('Endócrino', 'Endócrino'), ('Nervoso', 'Nervoso'), ('Reprodutivo', 'Reprodutivo'), ('Muscular', 'Muscular'), ('Esquelético', 'Esquelético'), ('Tegumentar', 'Tegumentar'), ('Excretor', 'Excretor')], max_length=104, null=True),
        ),
    ]
