# Generated by Django 2.2.4 on 2019-09-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0006_auto_20190909_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalmodel',
            old_name='cidade',
            new_name='id_cidade',
        ),
    ]
