# Generated by Django 2.2.4 on 2019-09-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0007_auto_20190909_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalmodel',
            old_name='id_cidade',
            new_name='cidade',
        ),
    ]
