# Generated by Django 2.2.4 on 2019-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudosMedvet', '0008_auto_20190909_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='complemento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='animalmodel',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
